#!/bin/bash
echo "enter your token"
read TOKEN
echo "Search..."
read SEARCH
FILE=$(date +%N|sha256sum|cut -c 1-16)
$HOME/.local/bin/ogs search $SEARCH|percol|grep -oP '[0,1,2,3,4,5,6,7,8,9]{5,}' > /tmp/$FILE;
RELEASE=$(cat /tmp/$FILE)
#ogs search $SEARCH|percol
clear;
$HOME/.local/bin/ogs release $RELEASE;
